### ISSUE TITLE
Nearchivuje Novinky, HN a SeznamZprávy

### ISSUE THREAD

**Issue by martycoo** [veproza/novinovyprogram#32]
Hlásím déle trvající chybku, zmíněné weby se nearchivují/nestahují. 
Lambdy a celý tenhle kód je mimo mé schopnosti, jsem jen pouhý uživatel.
Tak prosím, smutně koukám :)

**Comment by veproza** [comment]
Dík za upozornění, moc pravidelně to už nesleduju, tak občas přehlídnu, že se nějaká publikace snaží zachránit před krachem relaunchem webu :-)

Novinky a HN opraveny včetně historie. SeznamZprávy začaly posílat v HTML ještě větší hegeš, který mě nenapadá jak bez spuštění celého prohlížeče zpracovat. Možná v budoucnu ještě najdu chuť se v tom reklamním balastu s pár článkama nimrat a ještě to zprovozním, ale pro teď SeznamZprávy zůstanou nezpracované.
